### ISSUE TITLE
LessDisableUrlRewriting is not implemented

### ISSUE THREAD

**Issue by RaduPoe** [Jehran/LessMsbuildTasks#8] opened 2015-03-17 12:17 UTC
Hello,
I just found out that the LessDisableUrlRewriting switch is not implemented. It can be found only in the docu, but it is not parsed in LessCompiler.targets, neither in the NodelessCompile.cs. Seems like someone didn't checked also the implementation of this.

Is there any plan to support further this project?

Kind regards,
Radu

**Comment by Jehran** [comment] 2015-03-20 00:34
Duplicate of #5

**Closed by Jehran** 2015-03-20 00:34 UTC
